/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CustomFormInput: typeof import('./components/form/CustomFormInput.vue')['default']
    CustomSvgIcon: typeof import('./components/CustomSvgIcon.vue')['default']
    DynamicFormItem: typeof import('./components/form/CustomFormInput.vue')['default']
    DynamicItems: typeof import('./components/DynamicItems.vue')['default']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    FormContainer: typeof import('./components/form/FormContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
