/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CustomIcon: typeof import('./components/CustomIcon.vue')['default']
    CustomSvgIcon: typeof import('./components/CustomSvgIcon.vue')['default']
    DynamicForm: typeof import('./components/form/DynamicForm.vue')['default']
    DynamicFormItem: typeof import('./components/form/DynamicFormItem.vue')['default']
    IcsaSvgIcon: typeof import('./components/CustomSvgIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./components/Test.vue')['default']
  }
}
